### ISSUE TITLE
Is jelix dead?

### ISSUE THREAD

**Issue by fernhub** [jelix/jelix#342]
Most of the open issues are created by the author, the closed ones seem to be misunderstandings or questions about wrongly documented features, and the website of the framework seems stuck in the year 2005. 
Do you have any statistics of the usage of the fw in the industry?
Will a 2.0 version with a more modern syntax ever be released?

**Comment by foxmask** [comment]
no it's not dead. Laurent works on it and with it.
he will tell you everything.

**Comment by laurentj** [comment]
Sure, there are less users and contributors than in 2005, and it has not the success of Symfony.
But it is actively used in some projects like [Lizmap](https://github.com/3liz/lizmap-web-client).

Saying that the website is stuck in 2005, is exaggerated. Its design has already changed since 2005, and [there are regularly some news](https://jelix.org/en/news).

I would like more time to enhance more often the framework (and to respond to issues like yours :-) ). Maintaining a such framework takes already huge time. I'm open to any contribution, from the source code to the website and the documentation.
